;;; multi-term-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from multi-term.el

(autoload 'multi-term "multi-term" "\
Create new term buffer.
Will prompt you shell name when you type `C-u' before this command." t)
(autoload 'multi-term-next "multi-term" "\
Go to the next term buffer.
If OFFSET is `non-nil', will goto next term buffer with OFFSET.

(fn &optional OFFSET)" t)
(autoload 'multi-term-prev "multi-term" "\
Go to the previous term buffer.
If OFFSET is `non-nil', will goto previous term buffer with OFFSET.

(fn &optional OFFSET)" t)
(autoload 'multi-term-dedicated-open "multi-term" "\
Open dedicated `multi-term' window.
Will prompt you shell name when you type `C-u' before this command." t)
(autoload 'multi-term-dedicated-toggle "multi-term" "\
Toggle dedicated `multi-term' window." t)
(autoload 'multi-term-dedicated-select "multi-term" "\
Select the `multi-term' dedicated window." t)
(register-definition-prefixes "multi-term" '("multi-term-" "term-"))

;;; End of scraped data

(provide 'multi-term-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; multi-term-autoloads.el ends here
