;;; helm-fuzzy-find-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from helm-fuzzy-find.el

(autoload 'helm-fuzzy-find "helm-fuzzy-find" "\
Preconfigured `helm' for the fuzzy-find (\"ff\") shell command.
With ARG, read a directory first for searching.

(fn ARG)" t)
(register-definition-prefixes "helm-fuzzy-find" '("helm-"))

;;; End of scraped data

(provide 'helm-fuzzy-find-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-fuzzy-find-autoloads.el ends here
