;;; md4rd-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from md4rd.el

(autoload 'md4rd-login "md4rd" "\
Sign into the reddit system via OAuth, to allow use of authenticated endpoints." t)
(autoload 'md4rd-refresh-login "md4rd" "\
Refresh the OAuth authentication token (lifetime 3600 seconds)." t)
(autoload 'md4rd "md4rd" "\
Invoke the main mode." t)
(autoload 'mode-for-reddit "md4rd" "\
Invoke the main mode." t)
(autoload 'md4rd-mode "md4rd" "\
Invoke the main mode." t)
(register-definition-prefixes "md4rd" '("md4rd-"))

;;; End of scraped data

(provide 'md4rd-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; md4rd-autoloads.el ends here
