;;; helm-directory-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from helm-directory.el

(autoload 'helm-directory "helm-directory" "\
Selecting directory before select the file." t)
(autoload 'helm-directory-change "helm-directory" "\
Change `helm-directory-basedir' with helm interface." t)
(register-definition-prefixes "helm-directory" '("helm-directory-"))

;;; End of scraped data

(provide 'helm-directory-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-directory-autoloads.el ends here
