;;; helm-ls-hg-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from helm-ls-hg.el

(autoload 'helm-hg-find-files-in-project "helm-ls-hg" nil t)
(register-definition-prefixes "helm-ls-hg" '("helm-"))

;;; End of scraped data

(provide 'helm-ls-hg-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-ls-hg-autoloads.el ends here
