;;; gmail2bbdb-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from gmail2bbdb.el

(autoload 'gmail2bbdb-import-file "gmail2bbdb" "\
Import vCards from VCARD-FILE into BBDB.
If VCARD-FILE is a wildcard, import each matching file.
Existing BBDB records will be *overrided*.

(fn VCARD-FILE)" t)
(register-definition-prefixes "gmail2bbdb" '("gmail2bbdb-"))

;;; End of scraped data

(provide 'gmail2bbdb-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gmail2bbdb-autoloads.el ends here
