;;; ac-ispell-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from ac-ispell.el

(autoload 'ac-ispell-ac-setup "ac-ispell" "\
Add `ac-source-ispell' to `ac-sources' and enable `auto-complete' mode" t)
(autoload 'ac-ispell-setup "ac-ispell" "\
Declare auto-complete source based on `ac-ispell-requires'" t)
(register-definition-prefixes "ac-ispell" '("ac-ispell-"))

;;; End of scraped data

(provide 'ac-ispell-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ac-ispell-autoloads.el ends here
