;;; twittering-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from twittering-mode.el

(autoload 'twit "twittering-mode" "\
Start twittering-mode." t)
(register-definition-prefixes "twittering-mode" '("assocref" "case-string" "debug-print" "list-push" "twittering-"))

;;; End of scraped data

(provide 'twittering-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; twittering-mode-autoloads.el ends here
