;;; ac-helm-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from ac-helm.el

(autoload 'ac-complete-with-helm "ac-helm" "\
Select `auto-complete' candidates by `helm'.
It is useful to narrow candidates." t)
(register-definition-prefixes "ac-helm" '("helm-"))

;;; End of scraped data

(provide 'ac-helm-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ac-helm-autoloads.el ends here
