;;; powerline-evil-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from powerline-evil.el

(autoload 'powerline-evil-face "powerline-evil" "\
Function to select appropriate face based on `evil-state'.")
(register-definition-prefixes "powerline-evil" '("powerline-evil-tag"))


;;; Generated autoloads from powerline-evil-themes.el

(autoload 'powerline-evil-center-color-theme "powerline-evil-themes" "\
Powerline's center-evil them with the evil state in color." t)
(autoload 'powerline-evil-vim-theme "powerline-evil-themes" "\
Powerline's Vim-like mode-line with evil state at the beginning." t)
(autoload 'powerline-evil-vim-color-theme "powerline-evil-themes" "\
Powerline's Vim-like mode-line with evil state at the beginning in color." t)

;;; End of scraped data

(provide 'powerline-evil-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; powerline-evil-autoloads.el ends here
