;;; ace-mc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from ace-mc.el

(autoload 'ace-mc-add-multiple-cursors "ace-mc" "\
Use AceJump to add or remove multiple cursors.

`ace-mc-add-multiple-cursors' will prompt your for locations to add
multiple cursors.  If a cursor already exists at that location,
it will be removed.  This process continues looping until you
exit, for example by pressing return or escape.

Without a \\[universal-argument] prefix argument, use the default
AceJump jumping mode as described in
`ace-jump-mode-submode-list'.  When called interactively with one
or more \\[universal-argument] prefix arguments PREFIX, use the
corresponding mode from `ace-jump-mode-submode-list'.  For
example, by default
   \\[ace-mc-add-multiple-cursors] ==> `ace-jump-word-mode'
   \\[universal-argument] \\[ace-mc-add-multiple-cursors] ==> `ace-jump-char-mode'
   \\[universal-argument] \\[universal-argument] \\[ace-mc-add-multiple-cursors] ==> `ace-jump-line-mode'

If SINGLE-MODE is set to 't', don't loop.

When the region is active, prompt for AceJump matches based on matching strings.

(fn &optional PREFIX SINGLE-MODE)" t)
(autoload 'ace-mc-add-single-cursor "ace-mc" "\
Add a single multiple cursor.

This is a wrapper for `ace-mc-add-multiple-cursors', only adding
a single cursor.

PREFIX is passed to `ace-mc-add-multiple-cursors', see the
documentation there.

(fn &optional PREFIX)" t)
(register-definition-prefixes "ace-mc" '("ace-mc-"))

;;; End of scraped data

(provide 'ace-mc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ace-mc-autoloads.el ends here
