;;; github-elpa-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from github-elpa.el

(autoload 'github-elpa-build "github-elpa" "\
Github elpa build.")
(autoload 'github-elpa-commit "github-elpa" "\
Github elpa commit.")
(register-definition-prefixes "github-elpa" '("github-elpa-"))

;;; End of scraped data

(provide 'github-elpa-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; github-elpa-autoloads.el ends here
