;;; say-what-im-doing-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from say-what-im-doing.el

(defvar say-what-im-doing-mode nil "\
Non-nil if say-What-Im-Doing mode is enabled.
See the `say-what-im-doing-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `say-what-im-doing-mode'.")
(custom-autoload 'say-what-im-doing-mode "say-what-im-doing" nil)
(autoload 'say-what-im-doing-mode "say-what-im-doing" "\
This is a mode to make emacs say every command you invoke out

  loud. This uses OS X's \"say\" by default, but can be
  configured to use a different command line program - see
  say-what-im-doing-shell-command.

This is a global minor mode.  If called interactively, toggle the
`say-What-Im-Doing mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='say-what-im-doing-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "say-what-im-doing" '("say-what-im-doing-"))

;;; End of scraped data

(provide 'say-what-im-doing-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; say-what-im-doing-autoloads.el ends here
