;;; helm-robe-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from helm-robe.el

(autoload 'helm-robe-completing-read "helm-robe" "\


(fn PROMPT CHOICES &optional PREDICATE REQUIRE-MATCH &rest ARGS)")

;;; End of scraped data

(provide 'helm-robe-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-robe-autoloads.el ends here
