;;; helm-img-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from helm-img.el

(register-definition-prefixes "helm-img" '("helm-img-"))


;;; Generated autoloads from helm-img-bing.el

(autoload 'helm-img-bing "helm-img-bing" "\


(fn QUERY)" t)
(register-definition-prefixes "helm-img-bing" '("helm-img-bing-"))


;;; Generated autoloads from helm-img-dir.el

(autoload 'helm-img-dir "helm-img-dir" "\


(fn DIR)" t)
(register-definition-prefixes "helm-img-dir" '("helm-img-dir-make-candidates"))

;;; End of scraped data

(provide 'helm-img-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-img-autoloads.el ends here
