;;; ac-inf-ruby-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from ac-inf-ruby.el

(autoload 'ac-inf-ruby-enable "ac-inf-ruby" "\
Add `ac-source-inf-ruby' to `ac-sources' for this buffer.")
(register-definition-prefixes "ac-inf-ruby" '("ac-"))

;;; End of scraped data

(provide 'ac-inf-ruby-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ac-inf-ruby-autoloads.el ends here
