;;; github-notifier-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from github-notifier.el

(defalias 'github-notifier 'github-notifier-mode)
(defvar github-notifier-mode nil "\
Non-nil if Github-Notifier mode is enabled.
See the `github-notifier-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `github-notifier-mode'.")
(custom-autoload 'github-notifier-mode "github-notifier" nil)
(autoload 'github-notifier-mode "github-notifier" "\
Toggle github notifications count display in mode line (Github Notifier mode).
With a prefix argument ARG, enable Github Notifier mode if ARG is
positive, and disable it otherwise.  If called from Lisp, enable
the mode if ARG is omitted or nil.

(fn &optional ARG)" t)
(register-definition-prefixes "github-notifier" '("github-notifier-"))

;;; End of scraped data

(provide 'github-notifier-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; github-notifier-autoloads.el ends here
