;;; js3-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from js3.el

 (add-to-list 'auto-mode-alist '("\\.js$" . js3-mode))
(autoload 'js3-mode "js3" "\
Major mode for editing JavaScript code.

\\{js3-mode-map}" t)
(register-definition-prefixes "js3" '("char-is-" "deflocal" "js3" "lazy-detect" "neq" "with-buffer"))


;;; Generated autoloads from js3-mode.el

 (add-to-list 'auto-mode-alist '("\\.js$" . js3-mode))
(autoload 'js3-mode "js3-mode" "\
Major mode for editing JavaScript code.

\\{js3-mode-map}" t)
(register-definition-prefixes "js3-mode" '("char-is-" "deflocal" "js3" "lazy-detect" "neq" "with-buffer"))

;;; End of scraped data

(provide 'js3-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; js3-mode-autoloads.el ends here
