;;; helm-pass-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from helm-pass.el

(autoload 'helm-pass "helm-pass" "\
Helm interface for pass." t)
(register-definition-prefixes "helm-pass" '("helm-pass-"))

;;; End of scraped data

(provide 'helm-pass-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-pass-autoloads.el ends here
