;;; borg-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from borg.el

(register-definition-prefixes "borg" '("borg-"))


;;; Generated autoloads from borg-elpa.el

(register-definition-prefixes "borg-elpa" '("borg-" "package-"))

;;; End of scraped data

(provide 'borg-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; borg-autoloads.el ends here
