;;; web-mode-edit-element-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from web-mode-edit-element.el

(autoload 'web-mode-edit-element-minor-mode "web-mode-edit-element" "\
Minor mode to provide key-bindings for web-mode-edit-element functions

This is a minor mode.  If called interactively, toggle the
`web-mode-edit-element minor mode' mode.  If the prefix argument
is positive, enable the mode, and if it is zero or negative,
disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `web-mode-edit-element-minor-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "web-mode-edit-element" '("web-mode-edit-element-minor-mode-map"))


;;; Generated autoloads from web-mode-edit-element-attributes.el

(register-definition-prefixes "web-mode-edit-element-attributes" '("web-mode-edit-element-attributes-"))


;;; Generated autoloads from web-mode-edit-element-elements.el

(register-definition-prefixes "web-mode-edit-element-elements" '("web-mode-edit-element-elements-"))


;;; Generated autoloads from web-mode-edit-element-utils.el

(register-definition-prefixes "web-mode-edit-element-utils" '("web-mode-edit-element-utils-"))

;;; End of scraped data

(provide 'web-mode-edit-element-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; web-mode-edit-element-autoloads.el ends here
