;;; sauron-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from sauron.el

(autoload 'sauron-start "sauron" "\
Start sauron. If the optional parameter HIDDEN is non-nil,
don't show the sauron window.

(fn &optional HIDDEN)" t)
(autoload 'sauron-start-hidden "sauron" "\
Start sauron, but don't show the window." t)
(register-definition-prefixes "sauron" '("sauron-" "sr-"))


;;; Generated autoloads from sauron-appt.el

(register-definition-prefixes "sauron-appt" '("sauron-" "sr-appt-"))


;;; Generated autoloads from sauron-compilation.el

(register-definition-prefixes "sauron-compilation" '("sauron-"))


;;; Generated autoloads from sauron-dbus.el

(register-definition-prefixes "sauron-dbus" '("dbus-" "sauron-dbus-" "sr-"))


;;; Generated autoloads from sauron-elfeed.el

(register-definition-prefixes "sauron-elfeed" '("counting-unread" "elfeed-update-" "sauron-" "sr-elfeed-"))


;;; Generated autoloads from sauron-erc.el

(register-definition-prefixes "sauron-erc" '("sauron-" "sr-erc-"))


;;; Generated autoloads from sauron-identica.el

(register-definition-prefixes "sauron-identica" '("sauron-" "sr-identica-"))


;;; Generated autoloads from sauron-jabber.el

(register-definition-prefixes "sauron-jabber" '("sauron-" "sr-jabber-"))


;;; Generated autoloads from sauron-mu4e.el

(register-definition-prefixes "sauron-mu4e" '("sauron-mu4e-"))


;;; Generated autoloads from sauron-notifications.el

(register-definition-prefixes "sauron-notifications" '("sauron-notifications-" "sr-notifications-urgency-to-priority"))


;;; Generated autoloads from sauron-org.el

(register-definition-prefixes "sauron-org" '("sauron-"))


;;; Generated autoloads from sauron-tail.el

(register-definition-prefixes "sauron-tail" '("sauron-tail-" "st-filter-"))


;;; Generated autoloads from sauron-twittering.el

(register-definition-prefixes "sauron-twittering" '("sauron-" "sr-twit-"))


;;; Generated autoloads from sauron-zeroconf.el

(register-definition-prefixes "sauron-zeroconf" '("sauron-zeroconf-"))

;;; End of scraped data

(provide 'sauron-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; sauron-autoloads.el ends here
