;;; helm-unicode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from helm-unicode.el

(autoload 'helm-unicode "helm-unicode" "\
Precofigured `helm' for looking up unicode characters by name.

With prefix ARG, reinitialize the cache.

(fn ARG)" t)
(register-definition-prefixes "helm-unicode" '("helm-unicode-"))

;;; End of scraped data

(provide 'helm-unicode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-unicode-autoloads.el ends here
