;;; ac-html-bootstrap-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from ac-html-bootstrap.el

(autoload 'ac-html-bootstrap+ "ac-html-bootstrap" "\
Enable bootstrap ac-html completion" t)
(defalias 'company-web-bootstrap+ 'ac-html-bootstrap+)
(register-definition-prefixes "ac-html-bootstrap" '("ac-html-bootstrap-source-dir"))


;;; Generated autoloads from ac-html-fa.el

(autoload 'ac-html-fa+ "ac-html-fa" "\
Enable Font Awesome completion for `ac-html' or `company-web'" t)
(defalias 'company-web-fa+ 'ac-html-fa+)
(register-definition-prefixes "ac-html-fa" '("ac-html-fa-source-dir"))

;;; End of scraped data

(provide 'ac-html-bootstrap-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ac-html-bootstrap-autoloads.el ends here
