;;; helm-systemd-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from helm-systemd.el

(autoload 'helm-systemd "helm-systemd" nil t)
(register-definition-prefixes "helm-systemd" '("helm-system"))

;;; End of scraped data

(provide 'helm-systemd-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-systemd-autoloads.el ends here
