;;; helm-helm-commands-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from helm-helm-commands.el

(autoload 'helm-helm-commands "helm-helm-commands" "\
Select from helm commands to execute." t)
(register-definition-prefixes "helm-helm-commands" '("helm-"))

;;; End of scraped data

(provide 'helm-helm-commands-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-helm-commands-autoloads.el ends here
