;;; magit-find-file-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from magit-find-file.el

(autoload 'magit-find-file-completing-read "magit-find-file" "\
Use a completing read to open a file from git ls-files." t)
(register-definition-prefixes "magit-find-file" '("magit-find-file-"))

;;; End of scraped data

(provide 'magit-find-file-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; magit-find-file-autoloads.el ends here
