;;; erc-youtube-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from erc-youtube.el

(eval-after-load 'erc '(define-erc-module youtube nil "Display inlined info about youtube links in ERC buffer" ((add-hook 'erc-insert-modify-hook 'erc-youtube-show-info t) (add-hook 'erc-send-modify-hook 'erc-youtube-show-info t)) ((remove-hook 'erc-insert-modify-hook 'erc-youtube-show-info) (remove-hook 'erc-send-modify-hook 'erc-youtube-show-info)) t))
(register-definition-prefixes "erc-youtube" '("erc-youtube"))

;;; End of scraped data

(provide 'erc-youtube-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; erc-youtube-autoloads.el ends here
