;;; keymap-utils-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from keymap-utils.el

(autoload 'kmu-current-local-mapvar "keymap-utils" "\
Return the variable bound to the current local keymap.
Interactively also show the variable in the echo area.

(fn)" t)
(register-definition-prefixes "keymap-utils" '("kmu-"))

;;; End of scraped data

(provide 'keymap-utils-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; keymap-utils-autoloads.el ends here
