;;; erc-terminal-notifier-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from erc-terminal-notifier.el

(register-definition-prefixes "erc-terminal-notifier" '("erc-terminal-notifier-"))

;;; End of scraped data

(provide 'erc-terminal-notifier-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; erc-terminal-notifier-autoloads.el ends here
