;;; ahk-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from ahk-mode.el

(add-to-list 'auto-mode-alist '("\\.ahk\\'" . ahk-mode))
(autoload 'ahk-mode "ahk-mode" "\
Major mode for editing AutoHotkey script (AHK).

The hook functions in `ahk-mode-hook' are run after mode initialization.

Key Bindings
\\{ahk-mode-map}

(fn)" t)
(register-definition-prefixes "ahk-mode" '("ac-source-" "ahk-"))

;;; End of scraped data

(provide 'ahk-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ahk-mode-autoloads.el ends here
