;;; electric-spacing-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from electric-spacing.el

(autoload 'electric-spacing-mode "electric-spacing" "\
Toggle automatic surrounding space insertion (Electric Spacing mode).
With a prefix argument ARG, enable Electric Spacing mode if ARG is
positive, and disable it otherwise.  If called from Lisp, enable
the mode if ARG is omitted or nil.

This is a local minor mode.  When enabled, typing an operator automatically
inserts surrounding spaces.  e.g., `=' becomes ` = ',`+=' becomes ` += '.  This
is very handy for many programming languages.

(fn &optional ARG)" t)
(register-definition-prefixes "electric-spacing" '("electric-spacing-"))


;;; Generated autoloads from electric-spacing-cc-mode.el

(register-definition-prefixes "electric-spacing-cc-mode" '("electric-spacing-cc-mode-"))


;;; Generated autoloads from electric-spacing-emacs-lisp-mode.el

(register-definition-prefixes "electric-spacing-emacs-lisp-mode" '("electric-spacing-emacs-lisp-mode-"))


;;; Generated autoloads from electric-spacing-haskell-mode.el

(register-definition-prefixes "electric-spacing-haskell-mode" '("electric-spacing-haskell-mode-"))


;;; Generated autoloads from electric-spacing-org-mode.el

(register-definition-prefixes "electric-spacing-org-mode" '("electric-spacing-org-mode-"))


;;; Generated autoloads from electric-spacing-python-mode.el

(register-definition-prefixes "electric-spacing-python-mode" '("electric-spacing-python-mode-"))


;;; Generated autoloads from electric-spacing-rust-mode.el

(register-definition-prefixes "electric-spacing-rust-mode" '("electric-spacing-rust-mode-"))


;;; Generated autoloads from electric-spacing-text-mode.el

(register-definition-prefixes "electric-spacing-text-mode" '("electric-spacing-text-mode-"))

;;; End of scraped data

(provide 'electric-spacing-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; electric-spacing-autoloads.el ends here
