;;; graphene-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from graphene-editing.el

(register-definition-prefixes "graphene-editing" '("graphene-"))


;;; Generated autoloads from graphene-helper-functions.el

(register-definition-prefixes "graphene-helper-functions" '("comment-current-line-dwim" "create-new-buffer" "decrease-window-" "increase-window-" "insert-semicolon-at-end-of-line" "kill-" "newline-anywhere"))


;;; Generated autoloads from graphene-look.el

(register-definition-prefixes "graphene-look" '("graphene-"))


;;; Generated autoloads from graphene-projects.el

(register-definition-prefixes "graphene-projects" '("emacs-process-p" "graphene-" "pid-if-active-emacs-process"))

;;; End of scraped data

(provide 'graphene-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; graphene-autoloads.el ends here
