;;; kaleidoscope-evil-state-flash-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from kaleidoscope-evil-state-flash.el

(autoload 'kaleidoscope-evil-state-flash-setup "kaleidoscope-evil-state-flash" "\
Set up hooks to flash the keyboard when changing Evil states." t)
(autoload 'kaleidoscope-evil-state-flash-teardown "kaleidoscope-evil-state-flash" "\
Remove the hooks set up by 'kaleidoscope-evil-state-flash-setup'." t)
(register-definition-prefixes "kaleidoscope-evil-state-flash" '("kaleidoscope-evil-state-flash"))

;;; End of scraped data

(provide 'kaleidoscope-evil-state-flash-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; kaleidoscope-evil-state-flash-autoloads.el ends here
