;;; adafruit-wisdom-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from adafruit-wisdom.el

(autoload 'adafruit-wisdom-select "adafruit-wisdom" "\
Select a quote at random and return as a string.

Parse assuming the following RSS format:
     ((rss (channel (item ...) (item ...) (item ...) ...)))
where each item contains:
     (item (title nil \"the quote\") ...)
and we  need just \"the quote\".")
(autoload 'adafruit-wisdom "adafruit-wisdom" "\
Display one of Adafruit's quotes in the minibuffer.
If ARG is non-nil the joke will be inserted into the current
buffer rather than shown in the minibuffer.

(fn &optional ARG)" t)
(register-definition-prefixes "adafruit-wisdom" '("adafruit-wisdom-"))

;;; End of scraped data

(provide 'adafruit-wisdom-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; adafruit-wisdom-autoloads.el ends here
