;;; evil-mc-extras-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from evil-mc-extras.el

(autoload 'evil-mc-extras-mode "evil-mc-extras" "\
Toggle evil multiple cursors extras in a single buffer.

This is a minor mode.  If called interactively, toggle the
`Evil-Mc-Extras mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `evil-mc-extras-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'evil-mc-extras-initialize "evil-mc-extras" "\
Enable `evil-mc-extras-mode' in the current buffer.")
(autoload 'turn-on-evil-mc-extras-mode "evil-mc-extras" "\
Turn on `evil-mc-extras-mode' in the current buffer." t)
(autoload 'turn-off-evil-mc-extras-mode "evil-mc-extras" "\
Turn off `evil-mc-extras-mode' in the current buffer." t)
(register-definition-prefixes "evil-mc-extras" '("evil-mc-extras-key-map" "global-evil-mc-extras-mode"))


;;; Generated autoloads from evil-mc-extras-num.el

(register-definition-prefixes "evil-mc-extras-num" '("evil-mc-"))

;;; End of scraped data

(provide 'evil-mc-extras-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-mc-extras-autoloads.el ends here
