;;; diffview-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from diffview.el

(autoload 'diffview-current "diffview" "\
Show current diff buffer in a side-by-side view." t)
(autoload 'diffview-region "diffview" "\
Show current diff region in a side-by-side view." t)
(autoload 'diffview-message "diffview" "\
Show `message-mode' buffer in a side-by-side view.

This is useful for reading patches from mailing lists." t)
(register-definition-prefixes "diffview" '("diffview-"))

;;; End of scraped data

(provide 'diffview-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; diffview-autoloads.el ends here
