;;; helm-open-github-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from helm-open-github.el

(autoload 'helm-open-github-from-commit "helm-open-github" nil t)
(autoload 'helm-open-github-from-file "helm-open-github" nil t)
(autoload 'helm-open-github-from-issues "helm-open-github" "\


(fn ARG)" t)
(autoload 'helm-open-github-from-pull-requests "helm-open-github" nil t)
(register-definition-prefixes "helm-open-github" '("gh-issues-issue-list-closed" "helm-open-github-"))

;;; End of scraped data

(provide 'helm-open-github-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-open-github-autoloads.el ends here
