;;; kaleidoscope-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from kaleidoscope.el

(autoload 'kaleidoscope-start "kaleidoscope" "\
Connect to the device on 'kaleidoscope-device-port'." t)
(autoload 'kaleidoscope-quit "kaleidoscope" "\
Disconnect from the device." t)
(register-definition-prefixes "kaleidoscope" '("kaleidoscope-"))

;;; End of scraped data

(provide 'kaleidoscope-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; kaleidoscope-autoloads.el ends here
