;;; helm-flymake-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from helm-flymake.el

(autoload 'helm-flymake "helm-flymake" "\
helm interface for flymake.

(fn ARG)" t)
(register-definition-prefixes "helm-flymake" '("helm-"))

;;; End of scraped data

(provide 'helm-flymake-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-flymake-autoloads.el ends here
