;;; helm-books-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from helm-books.el

(autoload 'helm-books "helm-books" "\
Books searcher with helm interface." t)
(register-definition-prefixes "helm-books" '("helm-books-"))

;;; End of scraped data

(provide 'helm-books-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-books-autoloads.el ends here
