;;; org2web-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from org2web.el

(autoload 'org2web-add-project "org2web" "\
Add `project-config' to `org2web-projects'

(fn PROJECT-CONFIG)")
(autoload 'org2web-select-project "org2web" "\
Let user select a project then return its name.

(fn PROMPT &optional PROJECT-NAME)")
(autoload 'org2web-publish "org2web" "\


(fn &optional PROJECT-NAME PUBLISHING-DIRECTORY JOB-NUMBER UPDATE-TOP-N)" t)
(autoload 'org2web-new-post "org2web" "\
Setup a new post.

PROJECT-NAME: which project do you want to export
CATEGORY:     this post belongs to
FILENAME:     the file name of this post

Note that this function does not verify the category and filename, it is users'
responsibility to guarantee the two parameters are valid.

(fn &optional PROJECT-NAME CATEGORY FILENAME INSERT-FALLBACK-TEMPLATE)" t)
(register-definition-prefixes "org2web" '("org2web-"))


;;; Generated autoloads from org2web-config.el

(register-definition-prefixes "org2web-config" '("org2web-get-"))


;;; Generated autoloads from org2web-devtools.el

(register-definition-prefixes "org2web-devtools" '("org2web-devtools-repository-directory"))


;;; Generated autoloads from org2web-el2org.el

(register-definition-prefixes "org2web-el2org" '("org2web-el2org-"))


;;; Generated autoloads from org2web-export.el

(register-definition-prefixes "org2web-export" '("org2web-"))


;;; Generated autoloads from org2web-resource.el

(register-definition-prefixes "org2web-resource" '("org2web-prepare-theme-resources"))


;;; Generated autoloads from org2web-template.el

(register-definition-prefixes "org2web-template" '("org2web-"))


;;; Generated autoloads from org2web-util.el

(register-definition-prefixes "org2web-util" '("org2web-"))


;;; Generated autoloads from org2web-vars.el

(register-definition-prefixes "org2web-vars" '("org2web-"))


;;; Generated autoloads from org2web-webserver.el

(register-definition-prefixes "org2web-webserver" '("org2web-webserver-"))

;;; End of scraped data

(provide 'org2web-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org2web-autoloads.el ends here
