;;; company-try-hard-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from company-try-hard.el

(autoload 'company-try-hard "company-try-hard" "\
Offer completions from the first backend in `company-backends' that
offers candidates. If called again, use the next backend, and so on." t)
(register-definition-prefixes "company-try-hard" '("company-try-hard--last-index"))

;;; End of scraped data

(provide 'company-try-hard-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-try-hard-autoloads.el ends here
