;;; helm-smex-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from helm-smex.el

(autoload 'helm-smex "helm-smex" nil t)
(autoload 'helm-smex-major-mode-commands "helm-smex" nil t)
(register-definition-prefixes "helm-smex" '("helm-smex-"))

;;; End of scraped data

(provide 'helm-smex-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-smex-autoloads.el ends here
