;;; helm-emmet-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from helm-emmet.el

(autoload 'helm-emmet "helm-emmet" "\
Helm to preview or expand emmet-mode's snippets." t)
(register-definition-prefixes "helm-emmet" '("helm-"))

;;; End of scraped data

(provide 'helm-emmet-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-emmet-autoloads.el ends here
