;;; ace-flyspell-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from ace-flyspell.el

(autoload 'ace-flyspell-jump-word "ace-flyspell" nil t)
(autoload 'ace-flyspell-dwim "ace-flyspell" nil t)
(autoload 'ace-flyspell-setup "ace-flyspell" "\
Set up default keybindings." t)
(register-definition-prefixes "ace-flyspell" '("ace-flyspell-"))

;;; End of scraped data

(provide 'ace-flyspell-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ace-flyspell-autoloads.el ends here
