;;; helm-ack-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from helm-ack.el

(autoload 'helm-ack-pop-stack "helm-ack" nil t)
(autoload 'helm-ack "helm-ack" "\


(fn &optional DIR)" t)
(register-definition-prefixes "helm-ack" '("helm-"))

;;; End of scraped data

(provide 'helm-ack-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-ack-autoloads.el ends here
