;;; helm-ls-svn-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from helm-ls-svn.el

(autoload 'helm-ls-svn-ls "helm-ls-svn" "\
Use helm to list buffers/files in svn project.
If ARG is nil, only possible when called from Lisp code, don't check if current
buffer is under a svn project.

(fn &optional ARG)" t)
(register-definition-prefixes "helm-ls-svn" '("helm-"))

;;; End of scraped data

(provide 'helm-ls-svn-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-ls-svn-autoloads.el ends here
