;;; pandoc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from pandoc.el

(autoload 'pandoc-antiword "pandoc" "\
Convert `FILE' to DocBook using Antiword.

(fn FILE)")
(autoload 'pandoc-convert-file "pandoc" "\
Convert `FILE-PATH' as `INPUT-FORMAT' to `OUTPUT-FORMAT'.

(fn FILE-PATH INPUT-FORMAT OUTPUT-FORMAT)")
(autoload 'pandoc-convert-stdio "pandoc" "\
Convert `BODY' as `INPUT-FORMAT' to `OUTPUT-FORMAT'.

(fn BODY INPUT-FORMAT OUTPUT-FORMAT)")
(autoload 'pandoc-open-eww "pandoc" "\
Render `FILE' using EWW and Pandoc.

(fn FILE)" t)
(autoload 'pandoc-turn-on-advice-eww "pandoc" "\
When `eww-open-file' using Pandoc if the file is not HTML.

Remove advice if `ENABLE' equals `-1'.

(fn &optional ENABLE)")
(register-definition-prefixes "pandoc" '("pandoc-"))

;;; End of scraped data

(provide 'pandoc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pandoc-autoloads.el ends here
