;;; bbcode-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from bbcode-mode.el

(autoload 'bbcode-mode "bbcode-mode" "\
Major mode for writing BBCode markup.

\\{bbcode-mode-map}

(fn)" t)
(autoload 'bbcode-scratch "bbcode-mode" "\
Open *bbcode-scratch* buffer to quickly edit BBCode posts." t)
(add-to-list 'auto-mode-alist '("\\.bbcode$" . bbcode-mode))
(register-definition-prefixes "bbcode-mode" '("bbcode-"))

;;; End of scraped data

(provide 'bbcode-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; bbcode-mode-autoloads.el ends here
