;;; helm-github-stars-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from helm-github-stars.el

(autoload 'helm-github-stars-fetch "helm-github-stars" "\
Remove cache file before calling helm-github-stars." t)
(autoload 'helm-github-stars "helm-github-stars" "\
Show and Browse your github's stars." t)
(register-definition-prefixes "helm-github-stars" '("helm-github-stars-" "hgs/"))

;;; End of scraped data

(provide 'helm-github-stars-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-github-stars-autoloads.el ends here
