;;; company-suggest-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from company-suggest.el

(autoload 'company-suggest-google "company-suggest" "\
`company-mode' completion backend for Google suggestions.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(autoload 'company-suggest-wiktionary "company-suggest" "\
`company-mode' completion backend for Wiktionary suggestions.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "company-suggest" '("company-suggest-"))

;;; End of scraped data

(provide 'company-suggest-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-suggest-autoloads.el ends here
