;;; helm-orgcard-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from helm-orgcard.el

(autoload 'helm-orgcard "helm-orgcard" "\
Anything command for orgcard." t)
(register-definition-prefixes "helm-orgcard" '("hoc-"))

;;; End of scraped data

(provide 'helm-orgcard-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-orgcard-autoloads.el ends here
