;;; py-snippets-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from py-snippets.el

(autoload 'py-snippets-initialize "py-snippets" "\
Load the `yasnippet-snippets' snippets directory.")
(register-definition-prefixes "py-snippets" '("py-snippets-dir"))

;;; End of scraped data

(provide 'py-snippets-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; py-snippets-autoloads.el ends here
