;;; dired-toggle-sudo-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from dired-toggle-sudo.el

(autoload 'dired-toggle-sudo "dired-toggle-sudo" "\
Reopen current file or dired buffer with sudo.

If SUDO-USER is nil assume root.

If called with `universal-argument' (C-u), ask for username.

(fn &optional SUDO-USER)" t)
(register-definition-prefixes "dired-toggle-sudo" '("dired-toggle-sudo-"))

;;; End of scraped data

(provide 'dired-toggle-sudo-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dired-toggle-sudo-autoloads.el ends here
