;;; erc-tweet-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from erc-tweet.el

(eval-after-load 'erc '(define-erc-module tweet nil "Display inlined twits in ERC buffer" ((add-hook 'erc-insert-modify-hook 'erc-tweet-show-tweet t) (add-hook 'erc-send-modify-hook 'erc-tweet-show-tweet t)) ((remove-hook 'erc-insert-modify-hook 'erc-tweet-show-tweet) (remove-hook 'erc-send-modify-hook 'erc-tweet-show-tweet)) t))
(register-definition-prefixes "erc-tweet" '("erc-tweet"))

;;; End of scraped data

(provide 'erc-tweet-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; erc-tweet-autoloads.el ends here
