;;; github-pullrequest-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from github-pullrequest.el

(autoload 'github-pullrequest-new "github-pullrequest" "\
Create a new pull request." t)
(autoload 'github-pullrequest-checkout "github-pullrequest" "\
List open pull request and have the user select one to checkout." t)
(register-definition-prefixes "github-pullrequest" '("github-pullrequest-"))

;;; End of scraped data

(provide 'github-pullrequest-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; github-pullrequest-autoloads.el ends here
