;;; ox-epub-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from ox-epub.el

(autoload 'org-epub-export-to-epub "ox-epub" "\
Export the current buffer to an EPUB file.

ASYNC defines wether this process should run in the background,
SUBTREEP supports narrowing of the document, VISIBLE-ONLY allows
you to export only visible parts of the document, EXT-PLIST is
the property list for the export process.

(fn &optional ASYNC SUBTREEP VISIBLE-ONLY EXT-PLIST)" t)
(register-definition-prefixes "ox-epub" '("org-epub-"))

;;; End of scraped data

(provide 'ox-epub-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ox-epub-autoloads.el ends here
