;;; dired-toggle-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from dired-toggle.el

(autoload 'dired-toggle-quit "dired-toggle" "\
Quit action under `dired-toggle-mode'." t)
(autoload 'dired-toggle-find-file "dired-toggle" "\
Wraper for `dired-find-file', use `find-alternate-file' instead so will not
create new buffer when changing directory, and will keep `dired-toggle-mode' and
`dired-hide-details-mode' states after opening new direcoty." t)
(autoload 'dired-toggle-up-directory "dired-toggle" "\
Wraper for `dired-up-directory', use `find-alternate-file' instead so will
not create new buffer when changing directory, and will keep `dired-toggle-mode'
and `dired-hide-details-mode' states after opening new direcoty." t)
(autoload 'dired-toggle "dired-toggle" "\
Toggle current buffer's directory.

(fn &optional PREFIX)" t)
(autoload 'dired-toggle-project-root "dired-toggle" "\
Toggle current project root directory.

(fn &optional PREFIX)" t)
(register-definition-prefixes "dired-toggle" '("dired-toggle-"))

;;; End of scraped data

(provide 'dired-toggle-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dired-toggle-autoloads.el ends here
