;;; helm-bind-key-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from helm-bind-key.el

(autoload 'helm-bind-key "helm-bind-key" "\
Helm command for bind-key." t)
(register-definition-prefixes "helm-bind-key" '("hbk-create-sources"))

;;; End of scraped data

(provide 'helm-bind-key-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-bind-key-autoloads.el ends here
