;;; github-stars-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from github-stars.el

(autoload 'github-stars-browse-url "github-stars" "\
Prompt you for one of your github stars and open it in the web browser.

(fn OWNER/NAME)" t)
(autoload 'github-stars-list "github-stars" "\
Display a list of your github stars." t)
(register-definition-prefixes "github-stars" '("github-stars"))

;;; End of scraped data

(provide 'github-stars-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; github-stars-autoloads.el ends here
