;;; ac-html-angular-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from ac-html-angular.el

(autoload 'ac-html-angular+ "ac-html-angular" "\
Enable angular ac-html completion" t)
(defalias 'company-web-angular+ 'ac-html-angular+)
(register-definition-prefixes "ac-html-angular" '("ac-html-angular-source-dir"))

;;; End of scraped data

(provide 'ac-html-angular-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ac-html-angular-autoloads.el ends here
