;;; helm-dictionary-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from helm-dictionary.el

(autoload 'helm-dictionary "helm-dictionary" nil t)
(register-definition-prefixes "helm-dictionary" '("helm-"))

;;; End of scraped data

(provide 'helm-dictionary-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-dictionary-autoloads.el ends here
